var CHAMPIONS_DATA = {
  species: [
    "Abomasnow","Abomasnow-Mega","Absol","Absol-Mega","Aegislash","Aegislash-Blade","Aegislash-Shield",
    "Aerodactyl","Aerodactyl-Mega","Aggron","Aggron-Mega","Alakazam","Alakazam-Mega","Alcremie",
    "Alcremie-Caramel-Swirl","Alcremie-Lemon-Cream","Alcremie-Matcha-Cream","Alcremie-Mint-Cream",
    "Alcremie-Rainbow-Swirl","Alcremie-Ruby-Cream","Alcremie-Ruby-Swirl","Alcremie-Salted-Cream",
    "Alcremie-Vanilla-Cream","Altaria","Altaria-Mega","Ampharos","Ampharos-Mega","Annihilape",
    "Appletun","Araquanid","Arbok","Arcanine","Arcanine-Hisui","Archaludon","Ariados","Armarouge",
    "Aromatisse","Audino","Audino-Mega","Aurorus","Avalugg","Avalugg-Hisui","Azumarill","Banette",
    "Banette-Mega","Barbaracle","Barbaracle-Mega","Basculegion","Basculegion-Female","Basculegion-Male",
    "Bastiodon","Beartic","Beedrill","Beedrill-Mega","Bellibolt","Blastoise","Blastoise-Mega",
    "Blaziken","Blaziken-Mega","Camerupt","Camerupt-Mega","Castform","Castform-Rainy","Castform-Snowy",
    "Castform-Sunny","Ceruledge","Chandelure","Chandelure-Mega","Charizard","Charizard-Mega-X",
    "Charizard-Mega-Y","Chesnaught","Chesnaught-Mega","Chimecho","Chimecho-Mega","Clawitzer",
    "Clefable","Clefable-Mega","Cofagrigus","Conkeldurr","Corviknight","Crabominable","Crabominable-Mega",
    "Decidueye","Decidueye-Hisui","Dedenne","Delphox","Delphox-Mega","Diggersby","Ditto","Dragalge",
    "Dragalge-Mega","Dragapult","Dragonite","Dragonite-Mega","Drampa","Drampa-Mega","Eelektross",
    "Eelektross-Mega","Emboar","Emboar-Mega","Emolga","Empoleon","Espathra","Espeon","Excadrill",
    "Excadrill-Mega","Falinks","Falinks-Mega","Farigiraf","Feraligatr","Feraligatr-Mega","Flapple",
    "Flareon","Floette-Eternal","Floette-Mega","Florges","Florges-Blue","Florges-Orange","Florges-Red",
    "Florges-White","Florges-Yellow","Forretress","Froslass","Froslass-Mega","Furfrou","Furfrou-Dandy",
    "Furfrou-Debutante","Furfrou-Diamond","Furfrou-Heart","Furfrou-Kabuki","Furfrou-La-Reine",
    "Furfrou-Matron","Furfrou-Natural","Furfrou-Pharaoh","Furfrou-Star","Gallade","Gallade-Mega",
    "Garbodor","Garchomp","Garchomp-Mega","Gardevoir","Gardevoir-Mega","Garganacl","Gengar",
    "Gengar-Mega","Gholdengo","Glaceon","Glalie","Glalie-Mega","Glimmora","Glimmora-Mega","Gliscor",
    "Golurk","Golurk-Mega","Goodra","Goodra-Hisui","Gourgeist","Gourgeist-Jumbo","Gourgeist-Large",
    "Gourgeist-Medium","Gourgeist-Small","Greninja","Greninja-Mega","Grimmsnarl","Gyarados",
    "Gyarados-Mega","Hatterene","Hawlucha","Hawlucha-Mega","Heliolisk","Heracross","Heracross-Mega",
    "Hippowdon","Houndoom","Houndoom-Mega","Houndstone","Hydrapple","Hydreigon","Incineroar",
    "Infernape","Jolteon","Kangaskhan","Kangaskhan-Mega","Kingambit","Kleavor","Klefki","Kommo-o",
    "Krookodile","Leafeon","Liepard","Lopunny","Lopunny-Mega","Lucario","Lucario-Mega","Luxray",
    "Lycanroc","Lycanroc-Dusk","Lycanroc-Midday","Lycanroc-Midnight","Machamp","Malamar","Malamar-Mega",
    "Mamoswine","Manectric","Manectric-Mega","Maushold","Maushold-Family-of-Four",
    "Maushold-Family-of-Three","Mawile","Mawile-Mega","Medicham","Medicham-Mega","Meganium",
    "Meganium-Mega","Meowscarada","Meowstic","Meowstic-Female","Meowstic-Male","Meowstic-Mega",
    "Metagross","Metagross-Mega","Milotic","Mimikyu","Morpeko","Morpeko-Full-Belly","Morpeko-Hangry",
    "Mr. Rime","Mudsdale","Musharna","Ninetales","Ninetales-Alola","Noivern","Oranguru","Orthworm",
    "Overqwil","Palafin","Palafin-Hero","Palafin-Zero","Pangoro","Passimian","Pawmot","Pelipper",
    "Pidgeot","Pidgeot-Mega","Pikachu","Pinsir","Pinsir-Mega","Politoed","Polteageist",
    "Polteageist-Antique","Polteageist-Phony","Primarina","Pyroar","Pyroar-Female","Pyroar-Male",
    "Pyroar-Mega","Quaquaval","Qwilfish","Raichu","Raichu-Alola","Raichu-Mega-X","Raichu-Mega-Y",
    "Rampardos","Reuniclus","Rhyperior","Roserade","Rotom","Rotom-Fan","Rotom-Frost","Rotom-Heat",
    "Rotom-Mow","Rotom-Wash","Runerigus","Sableye","Sableye-Mega","Salazzle","Samurott",
    "Samurott-Hisui","Sandaconda","Sceptile","Sceptile-Mega","Scizor","Scizor-Mega","Scolipede",
    "Scolipede-Mega","Scovillain","Scovillain-Mega","Scrafty","Scrafty-Mega","Serperior","Sharpedo",
    "Sharpedo-Mega","Simipour","Simisage","Simisear","Sinistcha","Sinistcha-Masterpiece",
    "Sinistcha-Unremarkable","Skarmory","Skarmory-Mega","Skeledirge","Slowbro","Slowbro-Galar",
    "Slowbro-Mega","Slowking","Slowking-Galar","Slurpuff","Sneasler","Snorlax","Spiritomb",
    "Staraptor","Staraptor-Mega","Starmie","Starmie-Mega","Steelix","Steelix-Mega","Stunfisk",
    "Stunfisk-Galar","Swampert","Swampert-Mega","Sylveon","Talonflame","Tauros","Tauros-Paldea-Aqua",
    "Tauros-Paldea-Blaze","Tauros-Paldea-Combat","Tinkaton","Torkoal","Torterra","Toucannon",
    "Toxapex","Toxicroak","Trevenant","Tsareena","Typhlosion","Typhlosion-Hisui","Tyranitar",
    "Tyranitar-Mega","Tyrantrum","Umbreon","Vanilluxe","Vaporeon","Venusaur","Venusaur-Mega",
    "Victreebel","Victreebel-Mega","Vileplume","Vivillon","Vivillon-Archipelago","Vivillon-Continental",
    "Vivillon-Elegant","Vivillon-Fancy","Vivillon-Garden","Vivillon-High-Plains","Vivillon-Icy-Snow",
    "Vivillon-Jungle","Vivillon-Marine","Vivillon-Meadow","Vivillon-Modern","Vivillon-Monsoon",
    "Vivillon-Ocean","Vivillon-Poke-Ball","Vivillon-Polar","Vivillon-River","Vivillon-Sandstorm",
    "Vivillon-Savanna","Vivillon-Sun","Vivillon-Tundra","Volcarona","Watchog","Weavile","Whimsicott",
    "Wyrdeer","Zoroark","Zoroark-Hisui"
  ],

  items: [
    "Abomasite","Absolite","Aerodactylite","Aggronite","Alakazite","Altarianite","Ampharosite",
    "Aspear Berry","Audinite","Babiri Berry","Banettite","Barbaracite","Beedrillite","Big Root",
    "Black Belt","Black Glasses","Blastoisinite","Blazikenite","Bright Powder","Cameruptite",
    "Chandelurite","Charcoal","Charizardite X","Charizardite Y","Charti Berry","Cheri Berry",
    "Chesnaughtite","Chesto Berry","Chilan Berry","Chimechite","Choice Scarf","Chople Berry",
    "Clefablite","Coba Berry","Colbur Berry","Crabominite","Damp Rock","Delphoxite","Dragalgite",
    "Dragon Fang","Dragoninite","Drampanite","Eelektrossite","Emboarite","Excadrite","Expert Belt",
    "Fairy Feather","Falinksite","Feraligite","Floettite","Focus Band","Focus Sash","Froslassite",
    "Galladite","Garchompite","Gardevoirite","Gengarite","Glalitite","Glimmoranite","Golurkite",
    "Greninjite","Gyaradosite","Haban Berry","Hard Stone","Hawluchanite","Heat Rock","Heracronite",
    "Houndoominite","Icy Rock","Iron Ball","Kangaskhanite","Kasib Berry","Kebia Berry","King's Rock",
    "Leftovers","Leppa Berry","Life Orb","Light Ball","Light Clay","Lopunnite","Lucarionite",
    "Lum Berry","Magnet","Malamarite","Manectite","Mawilite","Medichamite","Meganiumite",
    "Mental Herb","Meowsticite","Metal Coat","Metagrossite","Metronome","Miracle Seed","Muscle Band",
    "Mystic Water","Never-Melt Ice","Occa Berry","Oran Berry","Passho Berry","Payapa Berry",
    "Pecha Berry","Persim Berry","Pidgeotite","Pinsirite","Poison Barb","Pyroarite","Quick Claw",
    "Raichunite X","Raichunite Y","Rawst Berry","Rindo Berry","Roseli Berry","Sablenite",
    "Sceptilite","Scizorite","Scolipite","Scope Lens","Scovillainite","Scraftinite","Sharp Beak",
    "Sharpedonite","Shed Shell","Shell Bell","Shuca Berry","Silk Scarf","Silver Powder","Sitrus Berry",
    "Skarmorite","Slowbronite","Smooth Rock","Soft Sand","Spell Tag","Staraptite","Starminite",
    "Steelixite","Swampertite","Tanga Berry","Twisted Spoon","Tyranitarite","Venusaurite",
    "Victreebelite","Wacan Berry","White Herb","Wide Lens","Wise Glasses","Yache Berry","Zoom Lens"
  ],

  moves: [
    "Accelerock","Acid Armor","Acid Spray","Acrobatics","Acupressure","Aerial Ace","After You","Agility",
    "Air Cutter","Air Slash","Alluring Voice","Ally Switch","Amnesia","Ancient Power","Apple Acid",
    "Aqua Cutter","Aqua Jet","Aqua Ring","Aqua Step","Aqua Tail","Armor Cannon","Aromatic Mist",
    "Assurance","Attract","Aura Sphere","Aura Wheel","Aurora Veil","Avalanche","Axe Kick",
    "Baby-Doll Eyes","Baneful Bunker","Barb Barrage","Baton Pass","Beak Blast","Beat Up","Belch",
    "Belly Drum","Bind","Bite","Bitter Blade","Bitter Malice","Blast Burn","Blaze Kick","Blizzard",
    "Block","Body Press","Body Slam","Bone Rush","Boomburst","Bounce","Brave Bird","Breaking Swipe",
    "Brick Break","Brutal Swing","Bug Bite","Bug Buzz","Bulk Up","Bulldoze","Bullet Punch","Bullet Seed",
    "Burn Up","Burning Jealousy","Calm Mind","Ceaseless Edge","Charge","Charge Beam","Charm",
    "Chilling Water","Chilly Reception","Circle Throw","Clanging Scales","Clangorous Soul","Clear Smog",
    "Close Combat","Coaching","Coil","Comeuppance","Confuse Ray","Copycat","Corrosive Gas","Cosmic Power",
    "Cotton Guard","Cotton Spore","Counter","Covet","Crabhammer","Cross Chop","Cross Poison","Crunch",
    "Crush Claw","Curse","Dark Pulse","Darkest Lariat","Dazzling Gleam","Decorate","Defog",
    "Destiny Bond","Detect","Dig","Dire Claw","Disable","Discharge","Dive","Double Hit","Double Team",
    "Double-Edge","Draco Meteor","Dragon Cheer","Dragon Claw","Dragon Dance","Dragon Darts",
    "Dragon Pulse","Dragon Rush","Dragon Tail","Drain Punch","Draining Kiss","Drill Peck","Drill Run",
    "Dual Wingbeat","Dynamic Punch","Earth Power","Earthquake","Eerie Impulse","Eerie Spell",
    "Electric Terrain","Electrify","Electro Ball","Electro Shot","Electroweb","Encore","Endeavor",
    "Endure","Energy Ball","Entrainment","Eruption","Expanding Force","Explosion","Extrasensory",
    "Extreme Speed","Facade","Fairy Lock","Fake Out","Fake Tears","Feather Dance","Feint","Fell Stinger",
    "Fickle Beam","Fiery Dance","Final Gambit","Fire Blast","Fire Fang","Fire Lash","Fire Punch",
    "Fire Spin","First Impression","Fissure","Flail","Flame Charge","Flamethrower","Flare Blitz",
    "Flash Cannon","Flatter","Fling","Flip Turn","Flower Trick","Fly","Flying Press","Focus Blast",
    "Focus Energy","Focus Punch","Follow Me","Forest's Curse","Foul Play","Freeze-Dry","Frenzy Plant",
    "Frost Breath","Future Sight","Gastro Acid","Giga Drain","Giga Impact","Gigaton Hammer","Glare",
    "Grass Knot","Grassy Glide","Grassy Terrain","Grav Apple","Gravity","Growth","Guard Split",
    "Guard Swap","Guillotine","Gunk Shot","Gyro Ball","Hammer Arm","Hard Press","Haze","Head Smash",
    "Headlong Rush","Heal Bell","Heal Pulse","Healing Wish","Heat Crash","Heat Wave","Heavy Slam",
    "Helping Hand","Hex","High Horsepower","High Jump Kick","Horn Drill","Horn Leech","Howl",
    "Hurricane","Hydro Cannon","Hydro Pump","Hyper Beam","Hyper Voice","Hypnosis","Ice Beam","Ice Fang",
    "Ice Hammer","Ice Punch","Ice Shard","Ice Spinner","Icicle Crash","Icicle Spear","Icy Wind",
    "Imprison","Infernal Parade","Inferno","Infestation","Ingrain","Instruct","Iron Defense","Iron Head",
    "Iron Tail","Jet Punch","King's Shield","Knock Off","Kowtow Cleave","Lash Out","Last Resort",
    "Last Respects","Lava Plume","Leaf Blade","Leaf Storm","Leech Life","Leech Seed","Life Dew",
    "Light Screen","Light of Ruin","Liquidation","Lock-On","Low Kick","Low Sweep","Lumina Crash","Lunge",
    "Mach Punch","Magic Powder","Magic Room","Magnet Rise","Magnetic Flux","Make It Rain",
    "Matcha Gotcha","Mean Look","Mega Kick","Megahorn","Memento","Metal Burst","Metal Sound",
    "Meteor Beam","Meteor Mash","Minimize","Mirror Coat","Misty Explosion","Misty Terrain","Moonblast",
    "Moonlight","Morning Sun","Mortal Spin","Mountain Gale","Mud Shot","Mud-Slap","Muddy Water",
    "Mystical Fire","Nasty Plot","Night Daze","Night Shade","Night Slash","No Retreat","Noble Roar",
    "Nuzzle","Outrage","Overheat","Pain Split","Parabolic Charge","Parting Shot","Payback","Perish Song",
    "Petal Blizzard","Petal Dance","Phantom Force","Pin Missile","Play Rough","Pluck","Poison Fang",
    "Poison Jab","Poison Powder","Pollen Puff","Poltergeist","Population Bomb","Pounce","Power Gem",
    "Power Shift","Power Split","Power Swap","Power Trick","Power Trip","Power Whip","Protect",
    "Psych Up","Psychic","Psychic Fangs","Psychic Noise","Psychic Terrain","Psycho Cut",
    "Psyshield Bash","Psyshock","Quash","Quick Attack","Quick Guard","Quiver Dance","Rage Fist",
    "Rage Powder","Raging Bull","Raging Fury","Rain Dance","Rapid Spin","Razor Shell","Recover",
    "Recycle","Reflect","Reflect Type","Rest","Reversal","Rising Voltage","Roar","Rock Blast",
    "Rock Polish","Rock Slide","Rock Tomb","Rock Wrecker","Role Play","Roost","Round","Sacred Sword",
    "Safeguard","Salt Cure","Sand Tomb","Sandstorm","Scald","Scale Shot","Scary Face",
    "Scorching Sands","Screech","Seed Bomb","Seismic Toss","Self-Destruct","Shadow Ball","Shadow Claw",
    "Shadow Punch","Shadow Sneak","Shed Tail","Sheer Cold","Shell Side Arm","Shell Smash","Shelter",
    "Simple Beam","Sing","Skill Swap","Skitter Smack","Sky Attack","Slack Off","Sleep Powder",
    "Sleep Talk","Sludge Bomb","Sludge Wave","Smack Down","Smart Strike","Snap Trap","Snarl","Snore",
    "Snowscape","Soak","Soft-Boiled","Solar Beam","Solar Blade","Sparkling Aria","Speed Swap",
    "Spicy Extract","Spikes","Spiky Shield","Spirit Break","Spirit Shackle","Spit Up","Spite","Spore",
    "Stealth Rock","Steel Beam","Steel Roller","Steel Wing","Sticky Web","Stockpile","Stomping Tantrum",
    "Stone Axe","Stone Edge","Stored Power","Storm Throw","Strength Sap","String Shot","Struggle",
    "Struggle Bug","Stuff Cheeks","Stun Spore","Substitute","Sucker Punch","Sunny Day","Super Fang",
    "Supercell Slam","Superpower","Surf","Swagger","Swallow","Sweet Kiss","Sweet Scent","Switcheroo",
    "Swords Dance","Synthesis","Syrup Bomb","Tail Slap","Tailwind","Taunt","Tearful Look","Teatime",
    "Teeter Dance","Temper Flare","Terrain Pulse","Thief","Thrash","Throat Chop","Thunder",
    "Thunder Fang","Thunder Punch","Thunder Wave","Thunderbolt","Tickle","Tidy Up","Topsy-Turvy",
    "Torch Song","Torment","Toxic","Toxic Spikes","Toxic Thread","Trailblaze","Transform","Tri Attack",
    "Trick","Trick Room","Trick-or-Treat","Triple Arrows","Triple Axel","Trop Kick","Twin Beam",
    "U-turn","Upper Hand","Uproar","Vacuum Wave","Venoshock","Volt Switch","Volt Tackle","Water Pulse",
    "Water Shuriken","Water Spout","Waterfall","Wave Crash","Weather Ball","Whirlpool","Whirlwind",
    "Wide Guard","Wild Charge","Will-O-Wisp","Wish","Wonder Room","Wood Hammer","Worry Seed","Wrap",
    "X-Scissor","Yawn","Zap Cannon","Zen Headbutt"
  ],

  abilities: [
    "Adaptability","Analytic","Anger Point","Armor Tail","Aroma Veil","Battle Armor","Berserk",
    "Big Pecks","Blaze","Bulletproof","Cheek Pouch","Chlorophyll","Clear Body","Cloud Nine",
    "Competitive","Compound Eyes","Contrary","Corrosion","Cud Chew","Curious Medicine","Cursed Body",
    "Cute Charm","Damp","Defiant","Disguise","Drizzle","Drought","Dry Skin","Fairy Aura","Flame Body",
    "Flash Fire","Flower Veil","Friend Guard","Frisk","Gale Wings","Good as Gold","Hospitality",
    "Huge Power","Hyper Cutter","Illusion","Infiltrator","Inner Focus","Intimidate","Leaf Guard",
    "Levitate","Lightning Rod","Limber","Liquid Voice","Magic Bounce","Magic Guard","Mirror Armor",
    "Mold Breaker","Moody","Multiscale","Natural Cure","No Guard","Oblivious","Overcoat","Overgrow",
    "Pixilate","Poison Touch","Prankster","Pressure","Protean","Queenly Majesty","Rain Dish",
    "Reckless","Regenerator","Rock Head","Rough Skin","Sand Rush","Sand Stream","Sand Veil","Scrappy",
    "Sharpness","Sheer Force","Snow Cloak","Snow Warning","Solar Power","Solid Rock","Soundproof",
    "Speed Boost","Stamina","Stance Change","Static","Sturdy","Supreme Overlord","Swift Swim",
    "Technician","Telepathy","Thick Fat","Torrent","Tough Claws","Toxic Debris","Trace","Unaware",
    "Unburden","Unnerve","Water Bubble","Zero to Hero"
  ]
};
